benchMark: transpose.c

	gcc -O3 -o transpose transpose.c
	./transpose 100 20
	./transpose 200 20
	./transpose 300 20
	./transpose 400 20
	./transpose 500 20
	./transpose 600 20
	./transpose 700 20
	# ./transpose 1000 20
	# ./transpose 2000 20
	# ./transpose 5000 20
	# ./transpose 10000 20

benchMark2: 
	./transpose 10000 50
	./transpose 10000 100
	./transpose 10000 500
	./transpose 10000 1000
	./transpose 10000 5000
